# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: jlingema.com
description: > # this means to ignore newlines until "baseurl:"
  <h2>Software Development & Computing</h2>
  <h3 class='subhead'>with a scientific background</h3>
  <p class='headline'>Experimental particle physicist with a background in computing, software development and data analysis with an eye for layout and presentation. Experienced in writing clear, well documented code in Python and C++. Passionate about problem solving. Works well in international teams. Proven ability to work and deliver under pressure.</p>
url: "" # the subpath of your site, e.g. /blog
baseurl: "http://jlingema.web.cern.ch/jlingema/test/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  enable_rouge: true

sass:
  sass_dir: node_modules/bootstrap-sass/assets/stylesheets
  style: compressed
